spring:
  application:
    name: kboot-camel


# Logging
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-40.40logger{0}){magenta} - %clr(%m){green}%n"

# Management
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
